apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    tier: application
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ceph.conf: |+
    [global]
    mon_host = {{ .Values.exporter.ceph.mons }}

  ceph.client.{{ .Values.exporter.ceph.user }}.keyring: |+
    [client.admin]
        key = {{ .Values.exporter.ceph.key }}